### ISSUE TITLE
descram  p  le_tcpdump.py

### ISSUE THREAD

**Issue by alessandromarras** [percival-desy/percival-characterization#15]
to descramble a tcpdump file, 
2 methods need to be called in the config file, that are named inconsistently

gather:
    method: descram  p  le_tcpdump 

    input: *input
    output: *output

    descram  p  le_tcpdump:
        descram  b  le_method: descram  b  le_tcpdump_2018_03_15ad

I think this comes from the file in percival-characterization/calibration/src/gather/adccal/methods being named descram  p  le_tcpdump.py
while percival-characterization/calibration/src/gather/adccal/methods/descram  b  le_methods/descram  b  le_tcpdump_2018_03_15ad.py

this is not a big issue (once one has learned that has to use 2 different spelling for the descram-b/p-ling methods, but it takes a bit for one to recognize the issue)
either correct the file name, or document somewhere the name difference.

**Comment by manuelakuhn** [comment]
Sorry this was a typo. Was fixed in commit 6c39a37af2d3a7f554ae74dc6a4b2d1b7a8d38f6
It is now named "descamble" consistently.
